### PR TITLE
Created UML Class diagram of ParkingSpot and User

### PR DESCRIPTION
**Pull request by 0nism**
I made the UML model of the ParkingSpot, let me know if it is ok

image

EDIT: Also add User UML from @corradopetrelli

### CODE REVIEW

**Comment by corradopetrelli** [comment]
According to me, it is ok!

**Comment by MargheritaRenieri** [comment]
It is ok!

**Comment by corradopetrelli** [comment]
@0nism @MargheritaRenieri check my commit please

**Comment by corradopetrelli** [comment]
image

**Comment by 0nism** [comment]
You should change MUNICIPALLY to MUNICIPALITY

**Comment by 0nism** [comment]
Ok to me everything is in place: waiting for @MargheritaRenieri for merge approval

**Pull request merged**
